#!/bin/bash
scriptdir=`dirname "$BASH_SOURCE"`
retry=0
while [ $retry -le 3 ] ; do
    ${scriptdir}/kkeps_controller.py -a off | grep -q 'switch is: close'
    if [ $? == 0 ] ; then
        break
    fi
    sleep 1
    echo retry: $retry
    retry=$((retry + 1))
done
